data_mining/urls.py
from django.conf.urls import url
from .app.views import main

urlpatterns = [
    url(r'^clustering/average-linkage/$', main.average_linkage, name='clustering-average-linkage'),
    url(r'^clustering/centroid-linkage/$', main.centroid_linkage, name='clustering-centroid-linkage'),
    url(r'^clustering/complete-linkage/$', main.complete_linkage, name='clustering-complete-linkage'),
    url(r'^clustering/single-linkage/$', main.single_linkage, name='clustering-single-linkage'),
    url(r'^clustering/k-means/$', main.k_means, name='clustering-k-means'),
]

kuliah/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .app.views import main

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', main.index, name='home'),
    url(r'^data-mining/', include('data_mining.urls', namespace='data-mining')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/backend-nav.html
<ul class='nav navbar-nav'>
    <li class='dropdown'>
        <a href='#' class='dropdown-toggle' data-toggle='dropdown'>Data Mining <span class="caret"></span>
        </a>
        <ul class='dropdown-menu'>
            <li class='dropdown-submenu'>
                <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                    Clustering
                </a>
                <ul class='dropdown-menu'>
                    <li>
                        <a href="{% url 'data-mining:clustering-average-linkage' %}">Average Linkage</a>
                    </li>
                    <li>
                        <a href="{% url 'data-mining:clustering-centroid-linkage' %}">Centroid Linkage</a>
                    </li>
                    <li>
                        <a href="{% url 'data-mining:clustering-complete-linkage' %}">Complete Linkage</a>
                    </li>
                    <li>
                        <a href="{% url 'data-mining:clustering-single-linkage' %}">Single Linkage</a>
                    </li>
                    <li>
                        <a href="{% url 'data-mining:clustering-k-means' %}">K-Means</a>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

templates/backend.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ title }}</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'adminlte/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/skins/_all-skins.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/iCheck/flat/blue.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/morris/morris.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/font-awesome-4.5.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/datepicker/datepicker3.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/daterangepicker/daterangepicker-bs3.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}">
    <link rel='stylesheet' href="{% static 'plugin/chosen/chosen.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/datatables.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/backend.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="{% static 'adminlte/plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
    <script src="{% static 'script/lib.js' %}"></script>
    <script src="{% static 'script/core.js' %}"></script>
    <script src="{% static 'script/sims.js' %}"></script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="{% static 'adminlte/dist/js/html5shiv.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/respond.min.js' %}"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue layout-top-nav">
<div class="wrapper">

    <header class="main-header">
        <nav class="navbar navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <a href="{% url 'home' %}" class="navbar-brand">KULIAH</a>
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse pull-left" id="navbar-collapse">
                    {% include "backend-nav.html" %}
                </div>
                <!-- /.navbar-collapse -->
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                </div>
                <!-- /.navbar-custom-menu -->
            </div>
            <!-- /.container-fluid -->
        </nav>
    </header>

    <div class="content-wrapper">
        <div class="container">
            <section class="content">
                <div class="row">
                    <div class='col-md-12'>
                        <div class="box box-primary">
                            <div class="box-header">
                                <h3 class="box-title">{{ title }}</h3>
                            </div>
                            <div id="main-block-content" class="box-body">
                                {% block content %}
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>

            </section>
        </div>
    </div>
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2014-2015 <a href="{% url 'home' %}">SIMS</a>.</strong> All rights reserved.
    </footer>
</div>

{% csrf_token %}
<script src="{% static 'adminlte/dist/js/jquery-ui.min.js' %}"></script>
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{% static 'script/datatables.min.js' %}"></script>
<script src="{% static 'script/moment.js' %}"></script>
<script src="{% static 'plugin/chosen/chosen.jquery.min.js' %}"></script>
<script src="{% static 'adminlte/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/morris/morris.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<script src="{% static 'adminlte/plugins/knob/jquery.knob.js' %}"></script>
<script src="{% static 'adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'adminlte/plugins/datepicker/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<script src="{% static 'adminlte/plugins/fastclick/fastclick.min.js' %}"></script>
<script src="{% static 'adminlte/dist/js/app.min.js' %}"></script>
</body>
</html>

templates/core.html
{% extends "backend.html" %}
{% block content %}
{% endblock %}